//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18046
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BritishMicro.TaskClerk.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BritishMicro.TaskClerk.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while creating the application context..
        /// </summary>
        internal static string AppContextCreateFailure {
            get {
                return ResourceManager.GetString("AppContextCreateFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ConfigImage {
            get {
                object obj = ResourceManager.GetObject("ConfigImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;ArrayOfTaskDescription xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;TaskDescription&gt;
        ///    &lt;Id&gt;136f6c6f-ef59-4568-ad07-a7fa1120b7ca&lt;/Id&gt;
        ///    &lt;Name&gt;Default&lt;/Name&gt;
        ///    &lt;Description&gt;Not for general use.&lt;/Description&gt;
        ///    &lt;NoNagMinutes&gt;1&lt;/NoNagMinutes&gt;
        ///    &lt;Colour&gt;NAME:Black&lt;/Colour&gt;
        ///    &lt;CustomFlags&gt;0&lt;/CustomFlags&gt;
        ///    &lt;IsPrivate&gt;false&lt;/IsPrivate&gt;
        ///    &lt;MenuColumn&gt;0&lt;/MenuColumn&gt;
        ///    &lt;Sequence&gt;0&lt;/Sequence&gt;
        ///    &lt;IsEvent&gt;fal [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DefaultTaskDescriptions {
            get {
                return ResourceManager.GetString("DefaultTaskDescriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TaskClerkSDK.dll
        ///zlib.dll
        ///BritishMicroWinLib.dll
        ///
        ///.
        /// </summary>
        internal static string ExcludeFileList {
            get {
                return ResourceManager.GetString("ExcludeFileList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PluginComponent
        ///PluginExporter
        ///PluginToolMenuItem
        ///PluginUserControl
        ///PluginOptionControl
        ///PluginNotifyMenuItem
        ///PluginPrintFormatter.
        /// </summary>
        internal static string ExcludePluginList {
            get {
                return ResourceManager.GetString("ExcludePluginList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ExportPic {
            get {
                object obj = ResourceManager.GetObject("ExportPic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
